added locking

diff --git a/db-arch b/db-arch
--- a/db-arch
+++ b/db-arch
@@ -1,8 +1,19 @@
 #!/bin/bash
-# $Id: db-arch,v 1.9 2003/06/05 00:01:24 judd Exp $
+# $Id: db-arch,v 1.10 2003/08/16 23:56:46 judd Exp $
 
 uid=`id -u`
 TMPDIR="/tmp/archpkg.$uid"
+repoid=1
+
+# check for locks
+if [ -f /tmp/.repolck.$repoid ]; then
+	owner=`/bin/ls -l /tmp/.repolck.$repoid | awk '{print $3}'`
+	echo "error: db generation is already in progress (started by $owner)"
+	exit 1
+fi
+
+# lock
+touch /tmp/.repolck.$repoid
 
 # RedHat's mktemp is broken...
 if [ -d /tmp/archpkg.$uid ]; then
@@ -24,3 +35,5 @@ echo "==> Generating Text Package List..." >&2
 mv packages.txt /home/ftp/current/setup/packages.txt
 
 rm -rf $TMPDIR
+# unlock
+rm -f /tmp/.repolck.$repoid
diff --git a/db-unstable b/db-unstable
--- a/db-unstable
+++ b/db-unstable
@@ -1,8 +1,19 @@
 #!/bin/bash
-# $Id: db-unstable,v 1.5 2003/05/25 23:50:02 judd Exp $
+# $Id: db-unstable,v 1.6 2003/08/16 23:56:46 judd Exp $
 
 uid=`id -u`
 TMPDIR="/tmp/archpkg.$uid"
+repoid=3
+
+# check for locks
+if [ -f /tmp/.repolck.$repoid ]; then
+        owner=`/bin/ls -l /tmp/.repolck.$repoid | awk '{print $3}'`
+        echo "error: db generation is already in progress (started by $owner)"
+        exit 1
+fi
+
+# lock
+touch /tmp/.repolck.$repoid
 
 # RedHat's mktemp is broken...
 if [ -d $TMPDIR ]; then
@@ -20,4 +31,6 @@ CVS_RSH=ssh CVSROOT=:ext:cvs.archlinux.org:/home/cvs-unstable cvs -q export -r C
 cd $TMPDIR/unstable && /arch/pkgdb 3
 
 rm -rf $TMPDIR
+# unlock
+rm -f /tmp/.repolck.$repoid
 
