added some sanity checks around the cvs export calls

diff --git a/db-extra b/db-extra
--- a/db-extra
+++ b/db-extra
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: db-extra,v 1.6 2004/07/03 20:28:11 judd Exp $
+# $Id: db-extra,v 1.7 2004/08/17 19:17:36 judd Exp $
 
 uid=`id -u`
 repoid=2
@@ -38,6 +38,10 @@ mkdir $TMPDIR; [ $? -gt 0 ] && exit 1
 echo "==> Generating Pacman Database for EXTRA..." >&2
 cd $TMPDIR
 CVS_RSH=ssh CVSROOT=:ext:cvs.archlinux.org:/home/cvs-extra cvs -q export -r CURRENT extra
+if [ $? -gt 0 ]; then
+	echo "==> CVS export failed!"
+	exit 1
+fi
 # check again
 if [ -d /tmp/.gensync ]; then
 	echo "error: someone else is currently running gensync!"
diff --git a/db-testing b/db-testing
--- a/db-testing
+++ b/db-testing
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: db-testing,v 1.6 2004/07/03 20:28:11 judd Exp $
+# $Id: db-testing,v 1.7 2004/08/17 19:17:36 judd Exp $
 
 uid=`id -u`
 repoid=4
@@ -39,12 +39,24 @@ echo "==> Generating Pacman Database for TESTING..." >&2
 cd $TMPDIR
 echo "--- CURRENT ---"
 CVS_RSH=ssh CVSROOT=:ext:cvs.archlinux.org:/home/cvs-arch cvs -q export -r TESTING arch
+if [ $? -gt 0 ]; then
+	echo "==> CVS export failed!"
+	exit 1
+fi
 mv arch/build/* . && rm -rf arch
 echo "--- EXTRA ---"
 CVS_RSH=ssh CVSROOT=:ext:cvs.archlinux.org:/home/cvs-extra cvs -q export -r TESTING extra
+if [ $? -gt 0 ]; then
+	echo "==> CVS export failed!"
+	exit 1
+fi
 cp -a extra/* . && rm -rf extra
 echo "--- UNSTABLE ---"
 CVS_RSH=ssh CVSROOT=:ext:cvs.archlinux.org:/home/cvs-unstable cvs -q export -r TESTING unstable
+if [ $? -gt 0 ]; then
+	echo "==> CVS export failed!"
+	exit 1
+fi
 cp -a unstable/* . && rm -rf unstable
 # check again
 if [ -d /tmp/.gensync ]; then
