Clean up printf-formatters for user messages
 - db-functions: getpkgfile: The .sig file extension should be part of
   the filename parameter, not part of the message format string.

 - db-functions: arch_repo_modify: Shouldn't use ${action}
   string-interpolation in the message format string.  Since the
   entire message is a command, and we're using @Q to escape arguments
   anyway, go ahead and just construct the entire command as a single
   string that way, and feed it to '%s'.

diff --git a/db-functions b/db-functions
--- a/db-functions
+++ b/db-functions
@@ -273,7 +273,7 @@ getpkgfile() {
 		error "Package %s not found!" "$1"
 		exit 1
 	elif [[ ! -f ${1}.sig ]]; then
-		error "Package signature %s.sig not found!" "$1"
+		error "Package signature %s not found!" "$1.sig"
 		exit 1
 	fi
 
@@ -450,8 +450,8 @@ arch_repo_modify() {
 
 	# package files for repo-add might be relative to repo dir
 	pushd "${dbfile%/*}" >/dev/null
-	/usr/bin/repo-${action} -q "${dbfile}" ${pkgs[@]} \
-		|| error "repo-${action} %s %s " "${dbfile@Q}" "${pkgs[*]@Q}"
+	/usr/bin/repo-${action} -q "${dbfile}" "${pkgs[@]}" \
+		|| error '%s' "repo-${action} ${dbfile@Q} ${pkgs[*]@Q}"
 	set_repo_permission "${repo}" "${arch}"
 	popd >/dev/null
 
