Update messages to make full use of printf formatters
libmakepkg messaging functions provide automatic access to gettext
(which we do not currently make use of) in addition to cleanly
separating data from message strings.

In order for this to work properly, pass argv correctly from die() to
libmakepkg's error()

diff --git a/db-functions b/db-functions
--- a/db-functions
+++ b/db-functions
@@ -40,7 +40,7 @@ script_lock() {
 	local LOCKDIR="$TMPDIR/.scriptlock.${0##*/}"
 	if ! mkdir "$LOCKDIR" >/dev/null 2>&1 ; then
 		local _owner="$(/usr/bin/stat -c %U $LOCKDIR)"
-		error "Script ${0##*/} is already locked by $_owner."
+		error "Script %s is already locked by %s." "${0##*/}" "$_owner"
 		exit 1
 	else
 		set_umask
@@ -51,7 +51,7 @@ script_lock() {
 script_unlock() {
 	local LOCKDIR="$TMPDIR/.scriptlock.${0##*/}"
 	if [ ! -d "$LOCKDIR" ]; then
-		warning "Script ${0##*/} was not locked!"
+		warning "Script %s was not locked!" "${0##*/}"
 		restore_umask
 		return 1
 	else
@@ -71,12 +71,12 @@ cleanup() {
 		repo=${l%.*}
 		arch=${l#*.}
 		if [ -d "$TMPDIR/.repolock.$repo.$arch" ]; then
-			msg "Removing left over lock from [${repo}] (${arch})"
+			msg "Removing left over lock from [%s] (%s)" "$repo" "$arch"
 			repo_unlock $repo $arch
 		fi
 	done
 	if [ -d "$TMPDIR/.scriptlock.${0##*/}" ]; then
-		msg "Removing left over lock from ${0##*/}"
+		msg "Removing left over lock from %s" "${0##*/}"
 		script_unlock
 	fi
 	rm -rf "$WORKDIR"
@@ -94,7 +94,7 @@ abort() {
 }
 
 die() {
-	error "$*"
+	error "$@"
 	cleanup 1
 }
 
@@ -114,7 +114,7 @@ repo_lock () {
 
 	# This is the lock file used by repo-add and repo-remove
 	if [ -f "${DBLOCKFILE}" ]; then
-		error "Repo [${1}] (${2}) is already locked by repo-{add,remove} process $(cat $DBLOCKFILE)"
+		error "Repo [%s] (%s) is already locked by repo-{add,remove} process %s" "$1" "$2" "$(cat $DBLOCKFILE)"
 		return 1
 	fi
 
@@ -131,8 +131,8 @@ repo_lock () {
 	while [ $_count -le $_trial ] || $_lockblock ; do
 		if ! mkdir "$LOCKDIR" >/dev/null 2>&1 ; then
 			_owner="$(/usr/bin/stat -c %U $LOCKDIR)"
-			warning "Repo [${1}] (${2}) is already locked by $_owner. "
-			msg2 "Retrying in $LOCK_DELAY seconds..."
+			warning "Repo [%s] (%s) is already locked by %s." "$1" "$2" "$_owner"
+			msg2 "Retrying in %s seconds..." "$LOCK_DELAY"
 		else
 			LOCKS[${#LOCKS[*]}]="$1.$2"
 			set_umask
@@ -142,14 +142,14 @@ repo_lock () {
 		let _count=$_count+1
 	done
 
-	error "Repo [${1}] (${2}) is already locked by $_owner. Giving up!"
+	error "Repo [%s] (%s) is already locked by %s. Giving up!" "$1" "$2" "$_owner"
 	return 1
 }
 
 repo_unlock () { #repo_unlock <repo-name> <arch>
 	local LOCKDIR="$TMPDIR/.repolock.$1.$2"
 	if [ ! -d "$LOCKDIR" ]; then
-		warning "Repo lock [${1}] (${2}) was not locked!"
+		warning "Repo lock [%s] (%s) was not locked!" "$1" "$2"
 		restore_umask
 		return 1
 	else
@@ -204,7 +204,7 @@ getpkgname() {
 
 	_name="$(_grep_pkginfo "$1" "pkgname")"
 	if [ -z "$_name" ]; then
-		error "Package '$1' has no pkgname in the PKGINFO. Fail!"
+		error "Package '%s' has no pkgname in the PKGINFO. Fail!" "$1"
 		exit 1
 	fi
 
@@ -217,7 +217,7 @@ getpkgver() {
 
 	_ver="$(_grep_pkginfo "$1" "pkgver")"
 	if [ -z "$_ver" ]; then
-		error "Package '$1' has no pkgver in the PKGINFO. Fail!"
+		error "Package '%s' has no pkgver in the PKGINFO. Fail!" "$1"
 		exit 1
 	fi
 
@@ -229,7 +229,7 @@ getpkgarch() {
 
 	_ver="$(_grep_pkginfo "$1" "arch")"
 	if [ -z "$_ver" ]; then
-		error "Package '$1' has no arch in the PKGINFO. Fail!"
+		error "Package '%s' has no arch in the PKGINFO. Fail!" "$1"
 		exit 1
 	fi
 
@@ -259,10 +259,10 @@ getpkgfile() {
 		error 'No canonical package found!'
 		exit 1
 	elif [ ! -f "${1}" ]; then
-		error "Package ${1} not found!"
+		error "Package %s not found!" "$1"
 		exit 1
 	elif [ ! -f "${1}.sig" ]; then
-		error "Package signature ${1}.sig not found!"
+		error "Package signature %s.sig not found!" "$1"
 		exit 1
 	fi
 
@@ -278,10 +278,10 @@ getpkgfiles() {
 
 	for f in ${@}; do
 		if  [ ! -f "${f}" ]; then
-			error "Package ${f} not found!"
+			error "Package %s not found!" "$f"
 			exit 1
 		elif [ ! -f "${f}.sig" ]; then
-			error "Package signature ${f}.sig not found!"
+			error "Package signature %s.sig not found!" "$f"
 			exit 1
 		fi
 	done
@@ -392,7 +392,7 @@ check_pkgrepos() {
 #usage: chk_license ${license[@]}"
 chk_license() {
 	local l
-	for l in ${@}; do
+	for l in "${@}"; do
 		in_array ${l} ${ALLOWED_LICENSES[@]} && return 0
 	done
 
@@ -428,12 +428,12 @@ set_repo_permission() {
 
 	if [ -w "${dbfile}" ]; then
 		local group=$(/usr/bin/stat --printf='%G' "$(dirname "${dbfile}")")
-		chgrp $group "${dbfile}" || error "Could not change group of ${dbfile} to $group"
-		chgrp $group "${filesfile}" || error "Could not change group of ${filesfile} to $group"
-		chmod g+w "${dbfile}" || error "Could not set write permission for group $group to ${dbfile}"
-		chmod g+w "${filesfile}" || error "Could not set write permission for group $group to ${filesfile}"
+		chgrp $group "${dbfile}" || error "Could not change group of %s to %s" "$dbfile" "$group"
+		chgrp $group "${filesfile}" || error "Could not change group of %s to %s" "$filesfile" "$group"
+		chmod g+w "${dbfile}" || error "Could not set write permission for group %s to %s" "$group" "$dbfile"
+		chmod g+w "${filesfile}" || error "Could not set write permission for group %s to %s" "$group" "$filesfile"
 	else
-		error "You don't have permission to change ${dbfile}"
+		error "You don't have permission to change %s" "$dbfile"
 	fi
 }
 
@@ -459,7 +459,7 @@ arch_repo_remove() {
 	local dbfile="${FTP_BASE}/${repo}/os/${arch}/${repo}${DBEXT}"
 
 	if [ ! -f "${dbfile}" ]; then
-		error "No database found at '${dbfile}'"
+		error "No database found at '%s'" "$dbfile"
 		return 1
 	fi
 	/usr/bin/repo-remove -q "${dbfile}" ${pkgs[@]} \
