Use common functions to print messages, warnings and errors
These functions are copied from makepkg

diff --git a/db-functions b/db-functions
--- a/db-functions
+++ b/db-functions
@@ -16,11 +16,48 @@ restore_umask () {
 WORKDIR=$(mktemp -d /tmp/$(basename $0).XXXXXXXXXX)
 LOCKS=()
 
+# check if messages are to be printed using color
+unset ALL_OFF BOLD BLUE GREEN RED YELLOW
+if [[ -t 2 ]]; then
+	ALL_OFF="$(tput sgr0)"
+	BOLD="$(tput bold)"
+	BLUE="${BOLD}$(tput setaf 4)"
+	GREEN="${BOLD}$(tput setaf 2)"
+	RED="${BOLD}$(tput setaf 1)"
+	YELLOW="${BOLD}$(tput setaf 3)"
+fi
+readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
+
+plain() {
+	local mesg=$1; shift
+	printf "${BOLD}    ${mesg}${ALL_OFF}\n" "$@"
+}
+
+msg() {
+	local mesg=$1; shift
+	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@"
+}
+
+msg2() {
+	local mesg=$1; shift
+	printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@"
+}
+
+warning() {
+	local mesg=$1; shift
+	printf "${YELLOW}==> WARNING:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+error() {
+	local mesg=$1; shift
+	printf "${RED}==> ERROR${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
 script_lock() {
 	local LOCKDIR="$TMPDIR/.scriptlock.$(basename $0)"
 	if ! mkdir "$LOCKDIR" >/dev/null 2>&1 ; then
 		local _owner="$(/usr/bin/stat -c %U $LOCKDIR)"
-		echo "Error: Script $(basename $0) is already locked by $_owner." >&2
+		error "Script $(basename $0) is already locked by $_owner."
 		exit 1
 	else
 		set_umask
@@ -31,7 +68,7 @@ script_lock() {
 script_unlock() {
 	local LOCKDIR="$TMPDIR/.scriptlock.$(basename $0)"
 	if [ ! -d "$LOCKDIR" ]; then
-		echo "Warning: Script $(basename $0) was not locked!" >&2
+		warning "Script $(basename $0) was not locked!"
 		restore_umask
 		return 1
 	else
@@ -51,12 +88,12 @@ cleanup() {
 		repo=${l%.*}
 		arch=${l#*.}
 		if [ -d "$TMPDIR/.repolock.$repo.$arch" ]; then
-			echo "Removing left over lock from $repo/$arch" >&2
+			msg "Removing left over lock from $repo/$arch"
 			repo_unlock $repo $arch
 		fi
 	done
 	if [ -d "$TMPDIR/.scriptlock.$(basename $0)" ]; then
-		echo "Removing left over lock from $(basename $0)" >&2
+		msg "Removing left over lock from $(basename $0)"
 		script_unlock
 	fi
 	rm -rf "$WORKDIR"
@@ -64,12 +101,12 @@ cleanup() {
 }
 
 abort() {
-	echo 'Aborting...' >&2
+	msg 'Aborting...'
 	cleanup 0
 }
 
 die() {
-	echo "$*" >&2
+	error "$*"
 	cleanup 1
 }
 
@@ -99,7 +136,8 @@ repo_lock () {
 	while [ $_count -le $_trial ] || $_lockblock ; do
 		if ! mkdir "$LOCKDIR" >/dev/null 2>&1 ; then
 			_owner="$(/usr/bin/stat -c %U $LOCKDIR)"
-			echo "Warning: Repo $1-$2 is already locked by $_owner. Retrying in $LOCK_DELAY seconds..." >&2
+			warning "Repo $1-$2 is already locked by $_owner. " \
+			        "Retrying in $LOCK_DELAY seconds..."
 		else
 			LOCKS[${#LOCKS[*]}]="$1.$2"
 			set_umask
@@ -109,14 +147,14 @@ repo_lock () {
 		let _count=$_count+1
 	done
 
-	echo "Error: Repo $1-$2 is already locked by $_owner. Giving up!" >&2
+	error "Repo $1-$2 is already locked by $_owner. Giving up!"
 	return 1
 }
 
 repo_unlock () { #repo_unlock <repo-name> <arch>
 	local LOCKDIR="$TMPDIR/.repolock.$1.$2"
 	if [ ! -d "$LOCKDIR" ]; then
-		echo "Warning: Repo lock $1-$2 was not locked!" >&2
+		warning "Repo lock $1-$2 was not locked!"
 		restore_umask
 		return 1
 	else
@@ -153,7 +191,7 @@ getpkgname() {
 
 	_name="$(_grep_pkginfo "$1" "^pkgname")"
 	if [ -z "$_name" ]; then
-		echo "Error: Package '$1' has no pkgname in the PKGINFO. Fail!" >&2
+		error "Package '$1' has no pkgname in the PKGINFO. Fail!"
 		exit 1
 	fi
 
@@ -166,7 +204,7 @@ getpkgver() {
 
 	_ver="$(_grep_pkginfo "$1" "^pkgver")"
 	if [ -z "$_ver" ]; then
-		echo "Error: Package '$1' has no pkgver in the PKGINFO. Fail!" >&2
+		error "Package '$1' has no pkgver in the PKGINFO. Fail!"
 		exit 1
 	fi
 
@@ -175,10 +213,10 @@ getpkgver() {
 
 getpkgfile() {
 	if [[ ${#} -ne 1 ]]; then
-		echo 'Error: No canonical package found!' >&2
+		error 'No canonical package found!'
 		exit 1
 	elif [ ! -f "${1}" ]; then
-		echo "Error: Package ${1} not found!" >&2
+		error "Package ${1} not found!"
 		exit 1
 	fi
 
@@ -188,13 +226,13 @@ getpkgfile() {
 getpkgfiles() {
 	local f
 	if [ ! -z "$(echo ${@%\.*} | sed "s/ /\n/g" | sort | uniq -D)" ]; then
-		echo 'Error: Duplicate packages found!'>&2
+		error 'Duplicate packages found!'
 		exit 1
 	fi
 
 	for f in ${@}; do
 		if  [ ! -f "${f}" ]; then
-			echo "Error: Package ${f} not found!" >&2
+			error "Package ${f} not found!"
 			exit 1
 		fi
 	done
@@ -208,7 +246,7 @@ check_pkg_arch () {
 	_arch="$(_grep_pkginfo "$1" "^arch")"
 
 	if [ -z "$_arch" ]; then
-		echo "Error: Package '$1' has no arch in the PKGINFO. Fail!" >&2
+		error "Package '$1' has no arch in the PKGINFO. Fail!"
 		return 1
 	fi
 	if [ "$_arch" = "$2" ]; then
diff --git a/misc-scripts/ftpdir-cleanup-repo b/misc-scripts/ftpdir-cleanup-repo
--- a/misc-scripts/ftpdir-cleanup-repo
+++ b/misc-scripts/ftpdir-cleanup-repo
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $# -ne 1 ]; then
-	echo "usage: $(basename $0) <reponame>"
+	msg "usage: $(basename $0) <reponame>"
 	exit 1
 fi
 
@@ -13,6 +13,7 @@ reponame=$1
 . "$(dirname $0)/../config"
 
 clean_pkgs () {
+  if ! ${CLEANUP_DRYRUN}; then
     for pkg in "$@"; do
         if [ -h "$pkg" ]; then
             rm -f "$pkg"
@@ -20,9 +21,10 @@ clean_pkgs () {
             mv "$pkg" "$CLEANUP_DESTDIR"
         fi
     done
+  fi
 }
 
-${CLEANUP_DRYRUN} && echo 'dry run mode is active'
+${CLEANUP_DRYRUN} && warning 'dry run mode is active'
 
 ftppath_base="$FTP_BASE/$reponame/os"
 
@@ -38,26 +40,23 @@ for arch in ${ARCHES[@]}; do
   EXTRAFILES=""
 
   if [ ! -d "$ftppath" ]; then
-      echo "FTP path '$ftppath' does not exist"
+      error "FTP path '$ftppath' does not exist"
       exit 1
   fi
 
   if ! cd "${CLEANUP_TMPDIR}" ; then
-      echo "Failed to cd to ${CLEANUP_TMPDIR}"
+      error "Failed to cd to ${CLEANUP_TMPDIR}"
       exit 1
   fi
 
   if [ ! -f "$ftppath/$reponame$DBEXT" ]; then
-    echo ""
-    echo "WARNING: The file \"$ftppath/$reponame$DBEXT\" could not be found, skipping."
-    echo ""
+    msg "The file \"$ftppath/$reponame$DBEXT\" could not be found, skipping."
     repo_unlock $reponame $arch
     continue
   fi
 
   if ! bsdtar xf "$ftppath/$reponame$DBEXT"; then
-    echo ""
-    echo "ERROR: Command failed: bsdtar xf \"$ftppath/$reponame$DBEXT\""
+    error "Command failed: bsdtar xf \"$ftppath/$reponame$DBEXT\""
     exit 1
   fi
 
@@ -106,7 +105,7 @@ for arch in ${ARCHES[@]}; do
   MISSINGFILES=""
   for mf in $missfiles; do
       if [ -e "${ftppath_base}/any/${mf}" ]; then
-          echo "Restoring missing 'any' symlink: ${mf}"
+          msg "Restoring missing 'any' symlink: ${mf}"
           ${CLEANUP_DRYRUN} || ln -s "../any/${mf}" "${ftppath}"
       else
           MISSINGFILES="${MISSINGFILES} ${mf}"
@@ -120,53 +119,36 @@ for arch in ${ARCHES[@]}; do
       continue
   fi
 
-  echo "Scan complete for $reponame ($arch) at ${ftppath}"
-
-  if [ -n "$DELETEFILES" ]; then
-      echo "    The following files are out of date"
-      for f in $DELETEFILES; do
-          echo "        $f"
-      done
-      echo ""
-  fi
-
-  if [ -n "$DELETESYMLINKS" ]; then
-      echo "    The following symlinks are out of date"
-      echo "    They will be deleted"
-      for f in $DELETESYMLINKS; do
-          echo "        $f"
-      done
-      echo ""
-  fi
+  msg "Scan complete for $reponame ($arch) at ${ftppath}"
 
   if [ -n "$MISSINGFILES" ]; then
-      echo "    The following files are missing in the repo"
       for f in $MISSINGFILES; do
-          echo "        $f"
-      done
-      echo ""
-  fi
-
-  if [ -n "$EXTRAFILES" ]; then
-      echo "    The following files are in the repo but not the db"
-      for f in $EXTRAFILES; do
-          echo "        $f"
+          error "$f is missing"
       done
   fi
 
   if [ -n "${DELETEFILES}" ]; then
-      ${CLEANUP_DRYRUN} || clean_pkgs ${DELETEFILES}
-      echo ""
+      msg "The following files are out of date"
+      for f in $DELETEFILES; do
+          msg2 "$f"
+      done
+      clean_pkgs ${DELETEFILES}
   fi
 
   if [ -n "${DELETESYMLINKS}" ]; then
-      ${CLEANUP_DRYRUN} || clean_pkgs ${DELETESYMLINKS}
-      echo ""
+      msg "The following symlinks are out of date"
+      for f in $DELETESYMLINKS; do
+          msg2 "$f"
+      done
+      clean_pkgs ${DELETESYMLINKS}
   fi
 
   if [ -n "${EXTRAFILES}" ]; then
-      ${CLEANUP_DRYRUN} || clean_pkgs ${EXTRAFILES}
-      echo ""
+      msg "The following files are in the repo but not the db"
+      for f in $EXTRAFILES; do
+          msg2 "$f"
+      done
+      clean_pkgs ${EXTRAFILES}
   fi
 
 done
@@ -193,15 +175,13 @@ if [ -d "$ftppath_base/any" ]; then
 fi
 
 if [ -n "$ARCHINDEPFILES" ]; then
-  echo "    The following architecture independent packages"
-  echo "    are not symlinked in the architecture repositories."
+  msg "The following architecture independent packages are not symlinked in the architecture repositories."
     for f in $ARCHINDEPFILES; do
-        echo "        $f"
+        msg2 "$f"
     done
 fi
 
 if [ -d "$ftppath_base/any" -a -n "${ARCHINDEPFILES}" ]; then
   cd "$ftppath_base/any"
-  ${CLEANUP_DRYRUN} || clean_pkgs ${ARCHINDEPFILES}
-  echo ""
+  clean_pkgs ${ARCHINDEPFILES}
 fi
