db-update: fix is_debug_package handling for any-packages on multi arch
For multi arch setups when handling any packages, we can't call
`getpkgbase` or `getpkgver` on the original `$pkg` location, as they get
moved along to a different location during looping through the arches.
This means we only have a single shot on `any` packages to collect all
the metadata that requires the actual package file at `$pkg` to exist.

Before this commit, the code only worked by sheer luck, as
is_debug_package will call `getpkgbase` via a subshell, which will
silently fail horribly as its run in a subshell. Fix this unexpected
behavior by only querying is_debug_package when the actual file still
exists. Any calls to is_debug_package with a none existing path are
now considered a fatal error.

Related-to: db-update: fix retrieving metadata from any-packages for multi arch

diff --git a/db-functions b/db-functions
--- a/db-functions
+++ b/db-functions
@@ -265,11 +265,16 @@ getpkgdesc() {
 #       here be dragons
 is_debug_package() {
 	local pkgfile=${1}
-	local pkgbase="$(getpkgbase "${pkgfile}")"
-	local pkgname="$(getpkgname "${pkgfile}")"
-	local pkgdesc="$(getpkgdesc "${pkgfile}")"
+	local pkgbase pkgname pkgdesc
 
-	[[ ${pkgdesc} == "Detached debugging symbols for "* && ${pkgbase}-debug = ${pkgname} ]]
+	if ! pkgbase="$(getpkgbase "${pkgfile}")" || \
+			! pkgname="$(getpkgname "${pkgfile}")" || \
+			! pkgdesc="$(getpkgdesc "${pkgfile}")"; then
+		error "Failed to get PKGINFO metadata from package '%s'" "${pkgfile}"
+		exit 1
+	fi
+
+	[[ ${pkgdesc} == "Detached debugging symbols for "* && ${pkgbase}-debug = "${pkgname}" ]]
 }
 
 check_packager() {
