git: use curated author information resolved by unix username
This should be a convenient way to automatically retrieve the author
informations for the state repository changes without the need of each
individual user to setup yet another author file.
This is a central service, hence we can easily deploy and generate the
authors file alongside the actual unix user and group permissions rolled
out by ansible.

diff --git a/db-functions b/db-functions
--- a/db-functions
+++ b/db-functions
@@ -295,6 +295,44 @@ check_builddir() {
 	[[ -n $_builddir && $_builddir = '/build' ]]
 }
 
+check_author() {
+	local author
+	if ! [[ -f "${AUTHORS}" ]]; then
+		die "No such authors file: '%s'" "${AUTHORS}"
+		return 1
+	fi
+	if ! author=$(get_author); then
+		return 1
+	fi
+	return 0
+}
+
+get_author() {
+	if ! username=$(/usr/bin/id -un); then
+		die "Failed to get username from 'id'"
+	fi
+	if ! author=$(grep -E " ${username}\$" "${AUTHORS}"); then
+		die "Missing author information for %s in '%s'" "${username}" "${AUTHORS}"
+	fi
+	echo "${author}"
+}
+
+get_author_name() {
+	local author=$1
+	if ! name=$(echo "${author}"|sed -E 's/(.+) (<.+>) .+/\1/'); then
+		die "Failed to get name from author line"
+	fi
+	echo "${name}"
+}
+
+get_author_email() {
+	local author=$1
+	if ! email=$(echo "${author}"|sed -E 's/(.+) (<.+>) .+/\2/'); then
+		die "Failed to get name from author line"
+	fi
+	echo "${email}"
+}
+
 # Non fatal getpkgfile expanding globs
 maybe_getpkgfile() {
 	if  (( $# != 1 )); then
diff --git a/db-functions-git b/db-functions-git
--- a/db-functions-git
+++ b/db-functions-git
@@ -98,7 +98,23 @@ pkgver_from_state_repo() {
 
 # Commit changes staged by (successive?) vcs_(re)?move_package runs.
 vcs_commit() {
-	arch_git -C "${GITREPO}" commit -m "${1}:" 
+	local commit_message=$1
+	local username author name email
+
+	if ! username=$(/usr/bin/id -un); then
+		die "Failed to get username from 'id'"
+	fi
+	if ! author=$(grep -E " ${username}\$" "${AUTHORS}"); then
+		die "Missing author information for %s in '%s'" "${username}" "${AUTHORS}"
+	fi
+	if ! name=$(echo "${author}"|sed -E 's/(.+) (<.+>) .+/\1/'); then
+		die "Failed to extract name from author line"
+	fi
+	if ! email=$(echo "${author}"|sed -E 's/(.+) (<.+>) .+/\2/'); then
+		die "Failed to extract email from author line"
+	fi
+
+	arch_git -c user.name="${name}" -c user.email="${email}" -C "${GITREPO}" commit -m "${commit_message}"
 }
 
 
