Cleanup missing db file logic
Do not touch missing db files. Additionally, no
need to call db-remove if the db file doesn't exist

Signed-off-by: Aaron Griffin <aaronmgriffin@gmail.com>

diff --git a/db-move b/db-move
--- a/db-move
+++ b/db-move
@@ -84,19 +84,14 @@ if [ -d "$packagename/repos/$svnrepo_from" ]; then
     # copy the db file into our working area
     if [ -f "$ftppath_from/$repofrom.db.tar.$DB_COMPRESSION" ]; then
         /bin/cp "$ftppath_from/$repofrom.db.tar.$DB_COMPRESSION" .
-    else
-        touch "$repofrom.db.tar.$DB_COMPRESSION"
+        /usr/bin/repo-remove "$repofrom.db.tar.$DB_COMPRESSION" $packagename || die "Error in repo-remove"
+        #use '*' to move the old DB too
+        mv $repofrom.db.tar.$DB_COMPRESSION* $ftppath_from
+        echo "    Package files will be cleaned up automatically"
     fi
-
-    /usr/bin/repo-remove "$repofrom.db.tar.$DB_COMPRESSION" $packagename || die "Error in repo-remove"
-    #use '*' to move the old DB too
-    mv $repofrom.db.tar.$DB_COMPRESSION* $ftppath_from
-    echo "    Package files will be cleaned up automatically"
 
     if [ -f "$ftppath_to/$repoto.db.tar.$DB_COMPRESSION" ]; then
         /bin/cp "$ftppath_to/$repoto.db.tar.$DB_COMPRESSION" .
-    else
-        touch "$repoto.db.tar.$DB_COMPRESSION"
     fi
 
     /bin/cp "$ftppath_from/$_pkgfile" .
