db-*: ensure we abort if we can't find the PKGBUILD
Signed-off-by: Morten Linderud <morten@linderud.pw>

diff --git a/db-move b/db-move
--- a/db-move
+++ b/db-move
@@ -34,9 +34,10 @@ for pkgbase in "${args[@]:2}"; do
 	found=false
 	for pkgarch in "${ARCHES[@]}"; do
 		if vcsrepo_from=$(find_repo_for_package "${pkgbase}" "${pkgarch}" "${repo_from}"); then
-			#FIXME: abort if PKGBUILD not there
-			_pkgver=$(cat "${GITREPO}/${vcsrepo_from}/${pkgbase}"| awk '{print $2}')
-			fetch_pkgbuild "${pkgbase}" "${_pkgver}"
+			_pkgver=$(awk '{print $2}' "${GITREPO}/${vcsrepo_from}/${pkgbase}")
+			if ! fetch_pkgbuild "${pkgbase}" "${_pkgver}"; then
+				die "Couldn't find package %s in git!" "${pkgbase}"
+			fi
 			read -rd'\n' pkgver pkgnames < <(source_pkgbuild "${pkgbase}" ""; \
 				get_full_version; echo "${pkgname[@]}")
 			read -ra pkgnames <<<"$pkgnames"
