Check permission before any action
Added a function to check if user has permission to alter the repos
and db files.

diff --git a/db-move b/db-move
--- a/db-move
+++ b/db-move
@@ -23,6 +23,11 @@ ftppath_to="$FTP_BASE/$repoto/os/"
 svnrepo_from="$repofrom-$arch"
 svnrepo_to="$repoto-$arch"
 
+if ! check_repo_permission $repoto || ! check_repo_permission $repofrom; then
+	echo "Error: You don't have permission to move packages from ${repofrom} to ${repoto}"
+	exit 1
+fi
+
 repo_lock $repoto $arch || exit 1
 repo_lock $repofrom $arch || exit 1
 
diff --git a/db-remove b/db-remove
--- a/db-remove
+++ b/db-remove
@@ -15,6 +15,11 @@ arch="$3"
 ftppath="$FTP_BASE/$reponame/os"
 svnrepo="$reponame-$arch"
 
+if ! check_repo_permission $reponame; then
+	echo "Error: You don't have permission to remove packages from ${reponam}"
+	exit 1
+fi
+
 repo_lock $reponame $arch || exit 1
 
 echo -n "Removing $packagebase from $reponame..."
