Prevent staging cleanup if copy to repo fails
This stops files being removed from the staging area if they were not
successfully copied to the repo.  This can happen due to permission
issues with the database when multiple people update the repo in quick
succession.

Original-work-by: Allan McRae <allan@archlinux.org>

Signed-off-by: Aaron Griffin <aaronmgriffin@gmail.com>

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -198,7 +198,9 @@ fi
 # if non empty, move all build dirs
 if [ $(/bin/ls "$WORKDIR/build/" 2>/dev/null | wc -l) != 0 ]; then
 	echo "Copying new files to '$ftppath'"
-	/bin/cp -r "$WORKDIR/build/"* "$ftppath" 
+	if ! /bin/cp -r "$WORKDIR/build/"* "$ftppath"; then
+		die "error: failure while copying files to $ftppath"
+	fi
 
 else
 	echo "Nothing to copy, no work done"
