changed mysql temp file so one user can run multiple db-gen scripts concurrently

diff --git a/db-unstable b/db-unstable
--- a/db-unstable
+++ b/db-unstable
@@ -1,9 +1,9 @@
 #!/bin/bash
-# $Id: db-unstable,v 1.9 2004/01/06 02:50:53 judd Exp $
+# $Id: db-unstable,v 1.10 2004/04/01 21:09:13 judd Exp $
 
 uid=`id -u`
-TMPDIR="/tmp/archpkg.$uid"
 repoid=3
+TMPDIR="/tmp/archpkg.$repoid.$uid"
 
 cleanup() {
 	rm -rf $TMPDIR
@@ -38,6 +38,11 @@ mkdir $TMPDIR; [ $? -gt 0 ] && exit 1
 echo "==> Generating Pacman Database for UNSTABLE..." >&2
 cd $TMPDIR
 CVS_RSH=ssh CVSROOT=:ext:cvs.archlinux.org:/home/cvs-unstable cvs -q export -r CURRENT unstable
+# check again
+if [ -d /tmp/.gensync ]; then
+	echo "error: someone else is currently running gensync!"
+	exit 1
+fi
 /usr/bin/gensync $TMPDIR/unstable $TMPDIR/unstable.db.tar.gz /home/ftp/unstable
 [ -f $TMPDIR/unstable.db.tar.gz ] && mv -f $TMPDIR/unstable.db.tar.gz /home/ftp/unstable
 
