Validate a package file's architecture
Apparently, people seem to be renaming files as a "hack" and
breaking things. Let's make sure they edited the PKGINFO too

Signed-off-by: Aaron Griffin <aaronmgriffin@gmail.com>

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -108,17 +108,23 @@ if [ -n "$ADDPKGS" ]; then
 	for pkg in $ADDPKGS; do
 		_pkgfile=$(basename $pkg)
 		_pkgname="$(getpkgname $pkg)"
-		echo "    Checking SVN for $_pkgname"
-		/usr/bin/svn up -q $_pkgname
-		if [ -d "$_pkgname/repos/$svnrepo" ]; then
-			. "$_pkgname/repos/$svnrepo/$BUILDSCRIPT"
-			if [ "$_pkgfile" = "$pkgname-$pkgver-$pkgrel-$CARCH$PKGEXT" ]; then
-				to_add="$to_add $pkg"
-			else
-				echo "    WARNING: $_pkgfile does not match $BUILDSCRIPT in $svnrepo"
-			fi
+
+		echo "    Validating package arch ($arch) $_pkgname"
+		if ! check_pkg_arch "$pkg" "$arch"; then
+			echo "   ERROR: $_pkgfile was built for the wrong architecture"
 		else
-			echo "    WARNING: Package $_pkgname not found in $svnrepo"
+			echo "    Checking SVN for $_pkgname"
+			/usr/bin/svn up -q $_pkgname
+			if [ -d "$_pkgname/repos/$svnrepo" ]; then
+				. "$_pkgname/repos/$svnrepo/$BUILDSCRIPT"
+				if [ "$_pkgfile" = "$pkgname-$pkgver-$pkgrel-$CARCH$PKGEXT" ]; then
+					to_add="$to_add $pkg"
+				else
+					echo "    WARNING: $_pkgfile does not match $BUILDSCRIPT in $svnrepo"
+				fi
+			else
+				echo "    WARNING: Package $_pkgname not found in $svnrepo"
+			fi
 		fi
 	done
 
