db-update: Fail if a set of split packages is incomplete

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -42,6 +42,9 @@ for repo in ${repos[@]}; do
 				die "Package ${repo}/$(basename ${pkg}) already exists in another repository"
 			fi
 		done
+		if ! check_splitpkgs ${repo} ${pkgs[@]}; then
+			die "Missing split packages for ${repo}"
+		fi
 	else
 		die "Could not read ${STAGING}"
 	fi
