db-update: die when trying to update a package without updating a pending rebuild
A semi-common pattern is for one maintainer to stage a rebuild of a
package due to e.g. cascading repository-wide python/boost/whatever
rebuilds, and then for the original maintainer of the package to not
notice and update the package in the stable repo, leaving an out of date
rebuild in staging or testing.

Then the the out of date package gets moved and ends up breaking things,
possibly via a package downgrade, possibly via breaking compatibility
with a much more targeted rebuild uploaded all at once. Ultimately,
Things Happen™ and the repository hierarchy gets broken.

Prevent this by enforcing for all packages that exist in
multiple levels of the repo: staging -> testing -> stable

That updates to one must come with an update to all the others.

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -52,6 +52,9 @@ for repo in "${repos[@]}"; do
 			if ! check_pkgrepos "${pkg}"; then
 				die "Package %s already exists in another repository" "$repo/${pkg##*/}"
 			fi
+			if ! missing_repo="$(check_stagingrepos "${pkg}" "${repo}")"; then
+				die "Package %s in %s needs to be updated in unstable repos as well: %s" "${pkg}" "${repo}" "${missing_repo}"
+			fi
 			if ! check_packager "${pkg}"; then
 				die "Package %s does not have a valid packager" "$repo/${pkg##*/}"
 			fi
