Don't try to update no package
Check if there are packages to update for given architecure. Previously
db-update quit when only one arch of a package was available.

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -60,10 +60,12 @@ for repo in ${repos[@]}; do
 			ln -s "../../../$(get_pkgpool_for_host)/${pkgfile}" "$FTP_BASE/$repo/os/${pkgarch}"
 			add_pkgs[${#add_pkgs[*]}]=${pkgfile}
 		done
-		pushd "$FTP_BASE/$repo/os/${pkgarch}" >/dev/null
-		/usr/bin/repo-add -q "$repo$DBEXT" ${add_pkgs[@]} >/dev/null \
-			|| die "Could not add packages"
-		popd >/dev/null
+		if [ ${#add_pkgs[@]} -ge 1 ]; then
+			pushd "$FTP_BASE/$repo/os/${pkgarch}" >/dev/null
+			/usr/bin/repo-add -q "$repo$DBEXT" ${add_pkgs[@]} >/dev/null \
+				|| die "Could not add packages"
+			popd >/dev/null
+		fi
 	done
 done
 
