Fail loudly if ftp dir is missing
This allows us to intuitively handle on-the-fly repos
by calling `db-update foobar i686` for the foobar-i686
tag, and let us fail on the server side if the repo
hasn't been approved/created by someone with admin rights.

Signed-off-by: Aaron Griffin <aaronmgriffin@gmail.com>

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -32,7 +32,13 @@ LOCKFILE="/tmp/.repolck.$arch.$reponame"
 ADDPKGS=""
 REMPKGS=""
 
-if [ ! `type -p fakeroot` ]; then
+if [ ! -d "$ftppath" ]; then
+	echo "FTP path for this repo ($reponame) is missing"
+	echo "Please contact a system administrator"
+	exit 1
+fi
+
+if [ ! $(type -p fakeroot) ]; then
 	echo "error: fakeroot is missing" >&2
 	exit 1
 fi
