db-*: ensure we abort if we can't find the PKGBUILD
Signed-off-by: Morten Linderud <morten@linderud.pw>

diff --git a/db-update b/db-update
--- a/db-update
+++ b/db-update
@@ -34,8 +34,9 @@ for repo in "${repos[@]}"; do
 	pkgs=($(getpkgfiles "${STAGING}/${repo}/"*${PKGEXTS}))
 	if (( $? == 0 )); then
 		for pkg in "${pkgs[@]}"; do
-			echo "$pkg"
-			fetch_pkgbuild "$(getpkgbase ${pkg})" "$(getpkgver ${pkg})"
+			if ! fetch_pkgbuild "$(getpkgbase ${pkg})" "$(getpkgver ${pkg})"; then
+				die "Couldn't find package %s in git!" "${pkg}"
+			fi
 		done
 	fi
 done
