Make repositories for testing2x configurable

diff --git a/testing2x b/testing2x
--- a/testing2x
+++ b/testing2x
@@ -10,7 +10,7 @@ fi
 
 # Lock everything to reduce  possibility of interfering task between the different repo-updates
 script_lock
-for repo in  'core' 'extra' 'testing'; do
+for repo in  ${TESTING_REPO} ${STABLE_REPOS[@]}; do
 	for pkgarch in ${ARCHES[@]}; do
 		repo_lock ${repo} ${pkgarch} || exit 1
 	done
@@ -24,16 +24,16 @@ for pkgbase in $*; do
 
 		found_source=false
 		for pkgarch in ${ARCHES[@]} 'any'; do
-			svnrepo_from="${WORKDIR}/${pkgbase}/testing-${pkgarch}"
+			svnrepo_from="${WORKDIR}/${pkgbase}/${TESTING_REPO}-${pkgarch}"
 			if [ -r "${svnrepo_from}/PKGBUILD" ]; then
 				found_source=true
 				break
 			fi
 		done
-		${found_source} || die "${pkgbase} not found in [testing]"
+		${found_source} || die "${pkgbase} not found in [${TESTING_REPO}]"
 		found_target=false
 		for pkgarch in ${ARCHES[@]} 'any'; do
-			for repo in 'core' 'extra'; do
+			for repo in ${STABLE_REPOS[@]}; do
 				svnrepo_to="${WORKDIR}/${pkgbase}/${repo}-${pkgarch}"
 				if [ -r "${svnrepo_to}/PKGBUILD" ]; then
 					found_target=true
@@ -42,19 +42,19 @@ for pkgbase in $*; do
 				fi
 			done
 		done
-		${found_target} || die "${pkgbase} neither found in [core] nor [extra]"
+		${found_target} || die "${pkgbase} not found in any of these repos: ${STABLE_REPOS[@]}"
 	fi
 done
 
 for pkgarch in ${ARCHES[@]}; do
-	repo_unlock 'testing' ${pkgarch}
+	repo_unlock ${TESTING_REPO} ${pkgarch}
 done
-for repo in  'core' 'extra'; do
+for repo in  ${STABLE_REPOS[@]}; do
 	for pkgarch in ${ARCHES[@]}; do
 		repo_unlock ${repo} ${pkgarch}
 	done
 	if [ -n "${pkgs[${repo}]}" ]; then
-		"$(dirname $0)/db-move" 'testing' "${repo}" ${pkgs[${repo}]}
+		"$(dirname $0)/db-move" ${TESTING_REPO} "${repo}" ${pkgs[${repo}]}
 	fi
 done
 
